In [ ]:
# Q.1 = Write statement to import numpy ? 

Q.2 = Create an array using numpy ? 

Q.3 = Create an array of 10 random integers ?

Q.4 = Create an array of elements from  10-20? 

Q.5 = Create an array which contains value 5 , 10 times ? 

Q.6 = Create a one dimensional array and convert that into 3*3 matrix ? 

Q.7 = Create a 2D array of size 3*3 but all the elements should be between 0 to 1 ? 

Q.8 = Concatenate 2D array horizontally and vertically ? 

# Q1, Q.2 = Create an array using numpy ? 

In [45]:
import numpy as np
a  = [1,2,3,4,5]
no = np.array(a)
no

array([1, 2, 3, 4, 5])

# Q.4 = Create an array of elements from  10-20? 


In [52]:
a = np.arange(10,21)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

# Q.5 = Create an array which contains value 5 , 10 times ? 


In [53]:
import numpy as np

a = np.full(10, 5)
a


array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

# Q.6 = Create a one dimensional array and convert that into 3*3 matrix ? 


In [54]:
a  = np.random.randint(1,18,9)

In [55]:
a

array([15,  8,  6, 12, 11,  9,  6,  5, 15])

In [58]:
a.reshape(3,3)

array([[15,  8,  6],
       [12, 11,  9],
       [ 6,  5, 15]])

# Q.7 = Create a 2D array of size 3*3 but all the elements should be between 0 to 1 ? 


In [62]:
a  =np.random.rand(3,3)
a

array([[0.47667862, 0.80316284, 0.32052937],
       [0.56195352, 0.07877863, 0.29643121],
       [0.20857662, 0.82142422, 0.90706238]])

# Q.8 = Concatenate 2D array horizontally and vertically ? 

In [63]:
import numpy as np

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Concatenate horizontally

concatenated_horizontal = np.concatenate((array1, array2), axis=1)
print("Horizontally concatenated array:")
print(concatenated_horizontal)

# Concatenate vertically
concatenated_vertical = np.concatenate((array1, array2), axis=0)
print("Vertically concatenated array:")
print(concatenated_vertical)


Horizontally concatenated array:
[[1 2 5 6]
 [3 4 7 8]]
Vertically concatenated array:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
